"use client";

import { SectionCard } from "@/components/shared/SectionCard";
import type { ReviewResultView } from "@/types/review";
import { ReviewScoreCard } from "./ReviewScoreCard";

type ReviewResultProps = {
  review: ReviewResultView;
};

export function ReviewResult({ review }: ReviewResultProps): JSX.Element {
  return (
    <div className="grid gap-6 xl:grid-cols-[280px_minmax(0,1fr)]">
      <ReviewScoreCard review={review} />
      <div className="space-y-6">
        <SectionCard
          title="Summary"
          description={`Generated by ${review.modelLabel}.`}
        >
          <p className="whitespace-pre-line text-sm leading-6 text-slate-700">{review.summary}</p>
        </SectionCard>
        <div className="grid gap-6 lg:grid-cols-3">
          <ReviewTextSection title="Strengths" content={review.strengths} />
          <ReviewTextSection title="Weaknesses" content={review.weaknesses} />
          <ReviewTextSection title="Suggestions" content={review.suggestions} />
        </div>
      </div>
    </div>
  );
}

type ReviewTextSectionProps = {
  title: string;
  content: string;
};

function ReviewTextSection({ title, content }: ReviewTextSectionProps): JSX.Element {
  return (
    <SectionCard title={title}>
      <p className="whitespace-pre-line text-sm leading-6 text-slate-700">{content}</p>
    </SectionCard>
  );
}
