"use client";

import { KpiCard } from "@/components/shared/KpiCard";
import { SectionCard } from "@/components/shared/SectionCard";
import type { PlannerPlanView, PlanPriorityValue } from "@/types/planner";

type PlannerFocusCardProps = {
  plan: PlannerPlanView;
};

export function PlannerFocusCard({ plan }: PlannerFocusCardProps): JSX.Element {
  return (
    <div className="grid gap-6 xl:grid-cols-[280px_minmax(0,1fr)]">
      <KpiCard
        title="Plan Priority"
        value={plan.priority}
        description={`Plan for ${plan.dateLabel}`}
        footer={`Generated ${plan.generatedAtLabel}`}
        tone={plan.priorityTone}
      />
      <SectionCard title="Focus Area" description={`Generated by ${plan.modelLabel}.`}>
        <div className="grid gap-6 lg:grid-cols-2">
          <PlannerList title="Priority Tasks" items={plan.priorityTasks} />
          <PlannerList title="Goals" items={plan.goals} />
          <PlannerList title="Risks" items={plan.risks} tone="risk" />
          <PlannerList title="Expected Outcomes" items={plan.expectedOutcomes} />
        </div>
      </SectionCard>
    </div>
  );
}

type PlannerListProps = {
  title: string;
  items: string[];
  tone?: "default" | "risk";
};

function PlannerList({ title, items, tone = "default" }: PlannerListProps): JSX.Element {
  const markerClass = tone === "risk" ? "bg-rose-500" : "bg-slate-400";

  return (
    <div className="space-y-3">
      <h3 className="text-sm font-semibold text-slate-950">{title}</h3>
      {items.length > 0 ? (
        <ul className="space-y-2">
          {items.map((item) => (
            <li key={`${title}-${item}`} className="flex gap-2 text-sm leading-6 text-slate-700">
              <span className={`mt-2 size-1.5 shrink-0 rounded-full ${markerClass}`} />
              <span>{item}</span>
            </li>
          ))}
        </ul>
      ) : (
        <p className="text-sm leading-6 text-slate-500">No items provided.</p>
      )}
    </div>
  );
}

export function getPriorityBadgeClass(priority: PlanPriorityValue): string {
  if (priority === "HIGH") {
    return "border-rose-200 bg-rose-50 text-rose-700";
  }

  if (priority === "MEDIUM") {
    return "border-amber-200 bg-amber-50 text-amber-700";
  }

  return "border-emerald-200 bg-emerald-50 text-emerald-700";
}
